export const menuData = {
  nonVeg: [
    { name: "Captain Chicken Cheesy Chipotle Burger", price: 229 },
    { name: "Captain Chipotle Double Cheese Burger", price: 299 },
    { name: "Captain's Club Chicken Drums (2pc)", price: 199 },
    { name: "Mackerel Popsicle (4pc)", price: 199 },
    { name: "Steam Chicken Momo", price: 189 },
    { name: "Fried Chicken Momo", price: 199 },
    { name: "Crispy Chicken Momo", price: 259 },
    { name: "Wings (2pc)", price: 199 },
    { name: "The Captain's Club Chicken Salad", price: 199 },
    { name: "Captain Chicken Chips Chaat", price: 199 },
  ],
  veg: [
    { name: "Paneer Corn Masala Cheesy Sandwich", price: 259 },
    { name: "Captain Paneer Cheesy Chipotle Burger", price: 199 },
    { name: "Chief Mate Cheesy Burger", price: 139 },
    { name: "Chief Mate Cheesy Chipotle Burger", price: 159 },
    { name: "Double Cheesy Burger", price: 169 },
    { name: "Double Cheesy Chipotle Burger", price: 189 },
    { name: "Captain Paneer Chips Chaat", price: 199 },
    { name: "Steam Paneer Momo", price: 199 },
    { name: "Steam Veg Momo", price: 177 },
    { name: "Crispy Veg Momo", price: 229 },
    { name: "Fried Soya Momo", price: 189 },
    { name: "Peri-Peri French Fries", price: 99 },
  ],
  beverages: [
    { name: "Masala Tea", price: 49 },
    { name: "Lemon Tea", price: 49 },
    { name: "Hot Coffee", price: 99 },
    { name: "Cold Coffee", price: 189 },
    { name: "Blue Lemonade", price: 149 },
    { name: "Vanilla Shake", price: 179 },
    { name: "Chocolate Shake", price: 179 },
    { name: "Oreo Shake", price: 179 },
    { name: "KitKat Shake", price: 179 },
    { name: "Blackcurrant Shake", price: 179 },
    { name: "Butterscotch Cold Coffee", price: 189 },
    { name: "Hazelnut Chocolate Shake", price: 249 },
    
  ],
  iceCream: {
    startingAt: 69,
    scoopPrices: {
      "1scoop": 99,
      "2scoop": 149,
    },
    flavors: [
      { name: "Chocolate", color: "bg-amber-700" },
      { name: "Vanilla", color: "bg-yellow-100" },
      { name: "Blackcurrant", color: "bg-purple-200" },
      { name: "American Bites", color: "bg-rose-100" },
      { name: "Jafrani Pista", color: "bg-lime-200" },
    ],
  },
};
